version: '3'
services:
  api-gateway:
    container_name: api-gateway
    image: cambo-registry.cambofreelance.com/keycloak/api-gateway:1
    ports:
      - "25010:25010"
    networks:
      - cf-network
networks:
  cf-network:
    external: true
