version: '3.8'
name: cf-team

services:
  api-gateway:
    image: nexus.cambofreelance.com/docker-hosted/api-gateway:v1.0.0
    container_name: api-gateway
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "25010:25010"
    environment:
        - SPRING_PROFILES_ACTIVE=dev
    networks:
      - cf-network

networks:
  cf-network:
    external: true
