server:
  port: 25010

spring:
  application:
    name: api-gateway
  r2dbc:
    url: r2dbc:postgresql://62.146.239.183:5511/dev_api_gateway
    username: keycloak
    password: keycloak
#    url: r2dbc:postgresql://localhost:12009/dev_api_gateway
#    username: postgres
#    password: CF@@2025

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 30000
      ssl:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloaks.cambofreelance.com:8443/realms/PBT-LOS

keycloak:
  url: https://keycloaks.cambofreelance.com:8443
  realm: PBT-LOS
  audience-client-id: los
  audience-client-secret: RGAfrkUc6z2zKoH0LOlO09kx8AelgTec
  username: admin
  password: admin
  enable: Y

logging:
  enable: true
  includeRequest: true
  includeRequestBody: true
  maskLogKey: maskingKey001,maskingkey001,masking-key-002 # its key is sensitive
  ignoreDefaultMaskingLogKey: ignoreMaskingKey001,ignoreMasking-key-002
  includeRequestHeader: true
  maxRequestBody: 1000 # its value is byte
  ignoreAntMatches: /abc,/zte-ba/**,/hiding-log # this value just example
  includeResponse: true
  includeResponseHeader: true
  maskResponseHeaderKey: maskingKey001,maskingkey001,masking-key-002 # its key isn't sensitive
  includeResponseBody: true
  maxResponseBody: 200 # its value is byte, the log size response
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
    console: "[%d] [%t] %-5level [${spring.application.name},%X{traceId},%X{spanId},%X{activityid}] %logger{36} - %msg%n"

otel:
  exporter:
    otlp:
      endpoint: http://alloy.monitoring:4317
      protocol: grpc
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,metrics,prometheus

authentication:
  jwtExpiration: 3600000 # 1 hour
  jwtRefreshExpiration: 2592000000 # 30 days in ms
  jwtSecret: b0aff574-a86e-4714-8108-63675311a839

storage:
  redis:
    key-response-code: key-response-code
    key-api-route: key-api-route

aes-cipher:
  gcm:
    key: UsLHzxoYLfUZ6sFbPs906dWmf3tulwJs/MfMAvT8SLk=
    algorithm: AES/GCM/NoPadding
    iv: ZGRFq4ZfB20=
    tag-size: 128
